### ISSUE TITLE
Key?

### ISSUE THREAD

**Issue by fxrsliberty** [Rohith050/mremoteng_to_remmina#1]
what keys are you talking about ?  my Remmina installation hasn't asked about nor generated any kind of key... as far as I know neither has my mRemoteNG

**Comment by Rohith050** [comment]
mRemoteNG uses an encryption key to encrypt the passwords of saved sessions, at least in the latest versions. You can check your config xml file to confirm this. Saved passwords will be in gibberish. By default mremoteng uses "mR3m" as the encryption key unless you changed it specifically.
Remmina also uses a key for the same purpose. Key is ideally located in ~/.config/remmina/remmina.pref file.
While installation either of these doesn't ask for keys. mremoteng uses a default key and remmina creates a random key.

Script needs both of these keys to decrypt mremoteng password and encrypt as remmina password.

Let me know how it goes..

**Comment by fxrsliberty** [comment]
I must be nuts,
In that prefs file there is a "secret=" line , I use the content after the
"=" sign as the "-rk"  and "mR3m" as the -mk. ????

**Comment by fxrsliberty** [comment]
mremoteng_to_remmina-main]$ 
python remmina_mremoteng_convertor.py -f mremote_export.xml -rk PX9s6ucM14yDLdgcMHodTDpV3scGA1YxVCxXstjuLRU=  -mk mR3m
Traceback (most recent call last):
  File "/home/jtremblay/mremoteng_to_remmina-main/remmina_mremoteng_convertor.py", line 291, in <module>
    handle_node(root)
  File "/home/jtremblay/mremoteng_to_remmina-main/remmina_mremoteng_convertor.py", line 289, in handle_node
    handle_node(child, group_name + '/' + child.attrib['Name'] if group_name else child.attrib['Name'])
  File "/home/jtremblay/mremoteng_to_remmina-main/remmina_mremoteng_convertor.py", line 289, in handle_node
    handle_node(child, group_name + '/' + child.attrib['Name'] if group_name else child.attrib['Name'])
  File "/home/jtremblay/mremoteng_to_remmina-main/remmina_mremoteng_convertor.py", line 276, in handle_node
    handle_ssh(child, group_name)
  File "/home/jtremblay/mremoteng_to_remmina-main/remmina_mremoteng_convertor.py", line 192, in handle_ssh
    local_skeleton['password'] = encrypt_remmina_password(decrypt_mremoteng_password(element.attrib['Password']))
  File "/home/jtremblay/mremoteng_to_remmina-main/remmina_mremoteng_convertor.py", line 182, in decrypt_mremoteng_password
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_GCM'

**Comment by fxrsliberty** [comment]
for python3 this seems to remove the encryption error but there still is no import
pip3 install pycryptodome

**Comment by fxrsliberty** [comment]
it doesn't directly import , duh . I need to read slower! :D

**Comment by fxrsliberty** [comment]
alas, remmina won't import the files created...  :(

**Comment by fxrsliberty** [comment]
there is nothing in the files :O

**Comment by Rohith050** [comment]
I am able to reproduce the issue. Somehow, the latest remmina version doesnt like the created session file. I manually created a session in remmina and compared the session file with the file created by the script and the content is almost the same. There are a couple of new fields. I added them into the file but that didnt help.  Also, the order of fields is different. I will try to update the order as per latest version. Hope it works.  Will update here ASAP.

**Comment by Rohith050** [comment]
Turned out to be permissions issue. I copied the created .remmina files to ~/.local/share/remmina/ folder and restarted remmina. All the sessions were imported successfully.

The folder might change depending on how you installed remmina.  Please check https://gitlab.com/Remmina/Remmina/-/issues/2178 for more info

'The native Remmina package, by default, store the `.remmina` file under `$HOME/.local/share/remmina`, while the snap under `$HOME/.var/app/org.remmina.Remmina/data/remmina`'

Please give it a try and let me know how it goes

**Comment by fxrsliberty** [comment]
I am still not able to import the converted files... 
Installed Packages
Name         : remmina
Version      : 1.4.20
Release      : 1.fc33
Architecture : x86_64
Size         : 3.8 M
Source       : remmina-1.4.20-1.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : Remote Desktop Client
URL          : http://remmina.org
License      : GPLv2+ and MIT
Description  : Remmina is a remote desktop client written in GTK+, aiming to be useful for
             : system administrators and travelers, who need to work with lots of remote
             : computers in front of either large monitors or tiny net-books.
             : 
             : Remmina supports multiple network protocols in an integrated and consistent
             : user interface. Currently RDP, VNC, XDMCP and SSH are supported.
             : 
             : Please don't forget to install the plugins for the protocols you want to use.

uname -a
Linux JT-Fedora-WKSTN 5.13.15-100.fc33.x86_64 #1 SMP Wed Sep 8 15:51:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/*-release
Fedora release 33 (Thirty Three)
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 33 (Thirty Three)
Fedora release 33 (Thirty Three)

**Comment by fxrsliberty** [comment]
![Screenshot from 2021-09-23 11-46-48](https://user-images.githubusercontent.com/7979168/134540583-848b26d1-e368-4482-830d-3e2725f3abb1.png)

this is what happens ... permissions are the same as the files created by the install.

**Comment by fxrsliberty** [comment]
![Screenshot from 2021-09-23 11-49-22](https://user-images.githubusercontent.com/7979168/134541006-4d009222-3a8d-43a3-85e3-688c17b6dfcf.png)

**Comment by fxrsliberty** [comment]
I got it ! under preferences I had chosen a different "Remmina data folder" moving the converted files to that location made them show up without intervention!

**Comment by Rohith050** [comment]
I am glad it worked out. I will try and update the documentation before closing.

**Comment by fxrsliberty** [comment]
Thanks for your help!

**Comment by ozgurerdogan** [comment]
Can you please guide me too, I am also having above errır that ends with:
cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_GCM'

**Comment by Rohith050** [comment]
@ozgurerdogan : Thanks for trying it out. May I know the version of python you are using? Script only works with python3.x. I have added a check in the script now.  Also, added requirements.txt which has all the needed modules. Please go through the updated readme file and let me know how it goes.

**Comment by ozgurerdogan** [comment]
Thank you @Rohith050  I finnaly succeed. Thank you very much. This is great script. One thing, remmina does not connect some rdp, it is probably about remmina and not about conversation right?

**Comment by Rohith050** [comment]
Tough to say without looking into .remmina file and logs.  If converted sessions had shown up in remmina, then most probably conversion happened correctly. Try creating the problematic RDP session manually and see if it works. If it works, them compare the .remmina file with converted file.  If you see any differences causing connectivity problem, I can update the script to handle those fields.

Closing this issue now. If needed, open a new issue for rdp sessions. Again, thanks for trying it out.

**Comment by ozgurerdogan** [comment]
I already tried that. And manual connection is also not succesfull. I found this https://gitlab.com/Remmina/Remmina/-/issues/2159

**Comment by Rohith050** [comment]
Cool. Nothing to fix my side then 😅
